name: Link Checker

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run link checker
      run: |
        python3 link_checker.py
        
    - name: Upload broken links report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: broken-links-report
        path: broken_links_report.md
        retention-days: 30
        
    - name: Comment on PR with broken links
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('broken_links_report.md')) {
            const report = fs.readFileSync('broken_links_report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🔗 Link Checker Report\n\nFound broken links in this PR:\n\n\`\`\`\n${report}\n\`\`\``
            });
          }