name: Lychee Link Checker

on:
  schedule:
    # Run weekly on Sundays at 3 AM UTC (offset from custom checker)
    - cron: '0 3 * * 0'
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Lychee Link Checker
      uses: lycheeverse/lychee-action@v1.9.3
      with:
        args: --verbose --no-progress '**/*.md'
        fail: true
        jobSummary: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Create Issue From File
      if: failure()
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "Link Checker Report - Broken Links Found"
        content-filepath: ./lychee/out.md
        labels: |
          bug
          documentation
          links