name: Lychee Link Checker

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/lychee-link-checker.yml'

jobs:
  linkChecker:
    name: Lychee Link Checker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './**/*.md' --exclude-file .lycheeignore
          fail: true
          format: markdown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Issue on Failure
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          
      - name: Upload Report as Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Link Checker Report
          path: ./lychee/out.md